### ISSUE TITLE
FieldValue valid

### ISSUE THREAD

**Issue by ghost** [b42inc/vue-form-validator#2]
もし可能でございましたらFieldValueをインスタンス化時の初期値に対してvalidの判定をしていただけるように調整していただきたいです。宜しくお願いいたします。

**Comment by naota70** [comment]
@kaneko-yutaka 
`init` イベントを FiledValue生成時に指定した場合にvalidationを通すようにしました（sample.vueのemail）。
よろしくおねがいします！
